name: Build APP

on:
  push:
    branches: [ "master", "old-android" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # 新增手动触发事件
    inputs:
      branch:
        description: 'Branch to run workflow'
        required: true
        default: 'main'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: sparkfabrik/android-build-action@v1.5.0
        with:
          project-path: .
          output-path: app-debug.apk
          fastlane-env: "debug"
          ruby-version: "3.3.0"
      - uses: actions/upload-artifact@v4
        if: github.event_name == 'pull_request'
        name: Upload app APK
        with:
          name: App bundle
          path: app-debug.apk
